Add registration api
fedor-ivn/nix-store-explorer pull request #10
Opened 2024-04-12 21:05 UTC by Probirochniy

2024-04-12 21:15 UTC, ilnarkhasanov commented
<img width="202" alt="image" src="https://github.com/fedor-ivn/nix-store-web/assets/37439026/4a8f3fce-662a-4686-b37e-c3ea408e17ac">

нам нужны концепции суперюзера, верифицированного юзера, активного?

2024-04-12 21:18 UTC, fedor-ivn commented
> <img alt="image" width="202" src="https://private-user-images.githubusercontent.com/37439026/322139728-4a8f3fce-662a-4686-b37e-c3ea408e17ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTY5OTQsIm5iZiI6MTcxMjk1NjY5NCwicGF0aCI6Ii8zNzQzOTAyNi8zMjIxMzk3MjgtNGE4ZjNmY2UtNjYyYS00Njg2LWIzN2UtYzNlYTQwOGUxN2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIxMTgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZTk3MGQ3NGIzNDU2MTNiN2Y5NDgxZTBkZmFhMmU3NzkxYWVmNDM3MGY3M2JmMDk1N2ZjYmNhNWNhMDBmOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KdwlztyXLYeJsOVc9LXn-kTQWaoUUMMK_-X6ebOgIxY">
> 
> нам нужны концепции суперюзера, верифицированного юзера, активного?

точно не нужны

2024-04-12 21:20 UTC, fedor-ivn commented on api/auth/auth.py
> +SECRET = "SECRET"
это в енвы надо выносить

2024-04-12 21:20 UTC, fedor-ivn commented on api/auth/database.py
> +DATABASE_URL = "sqlite+aiosqlite:///./auth_database.db"
это тоже в енвы

2024-04-12 21:22 UTC, fedor-ivn commented on api/auth/manager.py
> +        print(f"Verification requested for user {user.id}. Verification token: {token}")
этого у нас не просили => мертвый код => тесты на него писать не хочется => проседает coverage

вывод: на помойку

2024-04-12 21:27 UTC, fedor-ivn commented on api/auth/schemas.py
> +    is_verified: Optional[bool] = False
как сказал @ilnarkhasanov -- это extra features что ознает waste (мама мия), поэтому выпили это 🤌🤌🤌🤌🤌🤌🤌

2024-04-12 21:29 UTC, fedor-ivn commented on api/auth/auth.py
> +    get_strategy=get_jwt_strategy,
```suggestion
    get_strategy= lambda: JWTStrategy(secret=SECRET, lifetime_seconds=3600)
```

2024-04-12 21:29 UTC, fedor-ivn commented on api/auth/auth.py
> +    return JWTStrategy(secret=SECRET, lifetime_seconds=3600)
```suggestion
```

2024-04-12 21:31 UTC, fedor-ivn commented on api/auth/auth.py
> +cookie_transport = CookieTransport(cookie_max_age=3600)
имхо, можно не плодить переменную для такой штуки, а записать inline ниже 

и все вот эти константы типо 3600 тоже бы вынести наверное...

2024-04-12 21:33 UTC, fedor-ivn commented on api/auth/database.py
> +DATABASE_URL = "sqlite+aiosqlite:///./auth_database.db"
и кстати, если файлик с базой не существует, приложение его создаст? если нет, то наверное стоит такую логику сделать, чтобы уменьшить шаги, которые нужно сделать до запуска приложения

2024-04-12 21:34 UTC, Probirochniy commented on api/auth/schemas.py
> +    is_verified: Optional[bool] = False
убрать всё это дело - задача нетривиальная, потому что они изначально там уже есть в библиотеке. но щас попытаюсь

2024-04-12 21:35 UTC, Probirochniy commented on api/auth/auth.py
> +    get_strategy=get_jwt_strategy,
всё брал из примера в документации, там никаких лямбд..........

2024-04-12 21:36 UTC, ilnarkhasanov requested changes

2024-04-12 21:36 UTC, ilnarkhasanov commented on api/app.py
> +from fastapi import FastAPI
2 раза импортим

2024-04-12 21:36 UTC, fedor-ivn requested changes
🤌🤌🤌🤌

2024-04-12 21:36 UTC, Probirochniy commented on api/auth/auth.py
> +cookie_transport = CookieTransport(cookie_max_age=3600)
как сказал выше - это всё темплейт. не знаю, много ли смысла его трогать

2024-04-13 13:01 UTC, SnejUgal commented on api/auth/schemas.py
> +PYDANTIC_V2 = PYDANTIC_VERSION.startswith("2.")
🥴

2024-04-13 18:28 UTC, Probirochniy commented on api/auth/schemas.py
> +PYDANTIC_V2 = PYDANTIC_VERSION.startswith("2.")
![image](https://github.com/fedor-ivn/nix-store-web/assets/88425319/d1d3e8f8-fa6c-4268-b6ce-88e7fd97b6a7)

Ну почему вы все вините меня в том, что я взял прямо из сурсов библиотеки

2024-04-13 18:29 UTC, Probirochniy commented on api/auth/schemas.py
> +PYDANTIC_V2 = PYDANTIC_VERSION.startswith("2.")
С тем, что она написана очень странно, согласен

2024-04-13 18:30 UTC, SnejUgal commented on api/auth/schemas.py
> +PYDANTIC_V2 = PYDANTIC_VERSION.startswith("2.")
ну допустим, но в нашем проекте наверно можно обойтись и без проверки версии

2024-04-14 12:33 UTC, fedor-ivn approved these changes

2024-04-14 13:22 UTC, ilnarkhasanov commented
@Probirochniy 

давай в гитигнор закинем api/auth_database.db

в остальном с меня апрув

2024-04-15 10:40 UTC, ilnarkhasanov approved these changes

2024-04-15 11:56 UTC, SnejUgal commented on api/auth/schemas.py
> +PYDANTIC_V2 = PYDANTIC_VERSION.startswith("2.")
так, а щас это зачем?

2024-04-15 13:12 UTC, SnejUgal approved these changes

2024-04-15 17:33 UTC, merged