Delete payloads
fedor-ivn/nix-store-explorer pull request #15
Opened 2024-04-15 19:08 UTC by ilnarkhasanov

Closes #13

2024-04-15 19:37 UTC, SnejUgal approved these changes

2024-04-15 20:11 UTC, fedor-ivn approved these changes

2024-04-15 20:30 UTC, SnejUgal requested changes

2024-04-15 20:30 UTC, SnejUgal commented on streamlit/frontend.py
>          if store_id:
надо бы убрать весь код, связанный с получением `store_id`

2024-04-15 20:36 UTC, ilnarkhasanov commented on streamlit/frontend.py
>          if store_id:
@FurryLord 

возьми плиз на себя, у меня уже оверлоад задач получается

2024-04-16 17:10 UTC, FurryLord commented on streamlit/frontend.py
>          if store_id:
Done

2024-04-17 19:58 UTC, SnejUgal approved these changes

2024-04-17 20:30 UTC, merged