Add package
fedor-ivn/nix-store-explorer pull request #20
Opened 2024-04-21 14:00 UTC by ilnarkhasanov

2024-04-21 15:21 UTC, SnejUgal commented on api/logic/core.py
> +    return list(set(path["path"] for path in output))
так сет или лист?

2024-04-21 15:49 UTC, ilnarkhasanov commented on api/logic/core.py
> +    return list(set(path["path"] for path in output))
@SnejUgal 

сперва сет, чтобы дубликаты исключить, потом сет, чтобы в модель закинуть

2024-04-21 16:19 UTC, fedor-ivn commented on api/services/stores.py
> +        store_path = self.stores_path / f"{user.id}/{store_name}"
я наверное чот упускаю, но так точно не прокатит?

```
store_path = self.stores_path / user.id / store_name 
```

2024-04-21 16:23 UTC, fedor-ivn commented on pyproject.toml
> +    "api/stores",
такая директория существует разве?

2024-04-21 16:24 UTC, fedor-ivn submitted a review, later dismissed

2024-04-21 17:47 UTC, ilnarkhasanov commented on pyproject.toml
> +    "api/stores",
@fedor-ivn 

да, если обратишь внимание на сервис стора, то там задаётся папка где мы храним наши сторы

2024-04-21 17:48 UTC, ilnarkhasanov commented on pyproject.toml
> +    "api/stores",
<img width="709" alt="image" src="https://github.com/fedor-ivn/nix-store-web/assets/37439026/fed72853-eaf9-4f32-9664-d65121f4fc30">

2024-04-21 18:00 UTC, ilnarkhasanov commented on api/services/stores.py
> +        store_path = self.stores_path / f"{user.id}/{store_name}"
@fedor-ivn 

поправил, спасибо)

2024-04-21 18:04 UTC, SnejUgal approved these changes

2024-04-22 07:45 UTC, fedor-ivn requested changes
думаю стоит поправить локацию сторов

2024-04-22 08:06 UTC, fedor-ivn approved these changes

2024-04-22 08:11 UTC, SnejUgal approved these changes

2024-04-22 08:11 UTC, merged