Get stores difference
fedor-ivn/nix-store-explorer pull request #22
Opened 2024-04-22 16:27 UTC by ilnarkhasanov

2024-04-22 19:55 UTC, SnejUgal requested changes

2024-04-22 19:55 UTC, SnejUgal commented on api/store/router.py
> +        absent_in_store_1=difference_1,
чуть выше:

```py
difference_1: list[str] = list(store_1_paths - store_2_paths)
```

то есть `difference_1` — это пакеты, которые есть только в `store_1`. получается не `absent_in_store_1`, а наоборот, `present_in_store_1`

2024-04-22 20:03 UTC, fedor-ivn commented on api/store/models/package.py
> +    name: Mapped[str] = mapped_column(String(length=320), nullable=False)
а почему больше не unique=True?

2024-04-23 11:30 UTC, ilnarkhasanov commented on api/store/models/package.py
> +    name: Mapped[str] = mapped_column(String(length=320), nullable=False)
@fedor-ivn 

потому что у нас может быть один и тот же пакет в разных сторах

2024-04-23 17:31 UTC, SnejUgal approved these changes

2024-04-23 17:34 UTC, fedor-ivn approved these changes

2024-04-23 17:34 UTC, merged