Api testing
fedor-ivn/nix-store-explorer pull request #27
Opened 2024-04-24 08:18 UTC by fedor-ivn

2024-04-24 10:15 UTC, SnejUgal commented on .gitignore
> +
да чо вы по пустой строке везде оставляете...

2024-04-24 10:17 UTC, SnejUgal commented on api/tests/__init__.py
тесты может всё-таки уместнее в корне репы? особенно что после пакетирования в nix как-никак пришлось нормальную модульную систему завести

2024-04-24 10:46 UTC, snejugal commented on api/tests/unit/test_auth_endpoints.py
> +os.environ["DATABASE_URL"] = "sqlite+aiosqlite:///test.db"
🥴

мб аргументом в `create_db_and_tables` сделать?

2024-04-24 10:46 UTC, SnejUgal commented on api/tests/unit/test_auth_endpoints.py
> +os.environ["DATABASE_URL"] = "sqlite+aiosqlite:///test.db"
ну и да, ещё есть in-memory db: https://www.sqlite.org/inmemorydb.html

2024-04-24 10:46 UTC, snejugal commented on api/tests/unit/test_store_endpoints.py
> +    shutil.rmtree("stores", ignore_errors=True)
ну так сторы ж останутся, не? заюзай `delete_store` из логики, он всё нормально подчистит

2024-04-24 10:46 UTC, SnejUgal commented on api/tests/unit/test_store_logic.py
ух, я думал это на мне. ну ладно. в принципе тесты норм

2024-04-24 10:46 UTC, SnejUgal commented on pyproject.toml
> +pytest-cov = "^5.0.0"
а сам pytest?

2024-04-25 11:21 UTC, SnejUgal commented on pyproject.toml
> +locust = "^2.26.0"
мб в `[tool.poetry.groups.dev.dependency]` переставить?

2024-04-25 11:21 UTC, SnejUgal commented on pyproject.toml
> +locust = "^2.26.0"
и инномейни бы подмёржить с новой структурой... ну и тесты вынести из `api`, как выше писал

2024-04-25 11:35 UTC, Probirochniy commented on api/tests/unit/test_auth_endpoints.py
> +os.environ["DATABASE_URL"] = "sqlite+aiosqlite:///test.db"
Стоит, да. Сейчас там константа - неудобно. Отдельно тогда пулл открою
И да, про in-memory знаю, но сейчас его нормально не получается использовать, потому что метода чтобы закрыть соединение нет нормального, тесты друг на друга накладываются. Тоже попробую сделать

2024-04-25 11:36 UTC, Probirochniy commented on api/tests/unit/test_store_logic.py
Чёт даже не посмотрел, просто по папке api прошёлся. Облегчил работу, наверное

2024-04-26 07:29 UTC, SnejUgal requested changes

2024-04-26 07:29 UTC, snejugal commented on src/app.py
> +    main()
```suggestion
```

`python -m src`

2024-04-26 07:29 UTC, snejugal commented on src/logic/core.py
> +        Path(path).chmod(0o755)
а это зачем?

2024-04-26 07:29 UTC, snejugal commented on tests/test_frontend.py
> +                with patch("src.frontend.st.success") as mock_success:
```suggestion
    with (
        patch("src.frontend.requests.post") as mock_post,
        patch("src.frontend.st.button") as mock_button,
        patch("src.frontend.st.text_input") as mock_text_input,
        patch("src.frontend.st.success") as mock_success,
    ):
```

2024-04-28 15:39 UTC, Probirochniy commented on src/logic/core.py
> +        Path(path).chmod(0o755)
Там же так получается, что он меняет разрешения у родительской директории, что в итоге не помогает, если у основной не те. Возможно, конечно, я не так что-то понял

2024-04-28 17:18 UTC, SnejUgal commented on src/logic/core.py
> +        Path(path).chmod(0o755)
доходит дело до того, что надо удалить `/nix/store/a/b/c`. shutil не может этого сделать, потому что в `/nix/store/a/c` нельзя писать, соответственно менять содержимое директории тоже нельзя. поэтому нужно `/nix/store/a/c` сделать доступным на запись, и тогда файл получится удалить.

разрешения на самом файле (который сюда передаётся как `path`) значения тут не имеют. не имеют значения и разрешения на родителях `/nix/store/a/b`, потому что этих родителей мы не трогаем (да и тогда юзеры не могли бы ничего делать в своих домашних директориях, потому что им нельзя писать в `/`)

2024-04-28 18:45 UTC, snejugal commented on tests/unit/test_store_logic.py
```
ERROR tests/unit/test_store_logic.py::test_create_store - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_remove_store - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_remove_store_permission_error - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_remove_store_no_store - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_get_paths - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_install_package - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_install_package_called_process_error - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_install_package_unfree_licence - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_install_package_not_available_on_host_platform - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_install_package_attribute_not_provided - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_install_package_broken_package - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_install_package_insecure_package - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_remove_package - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_remove_package_still_alive - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_remove_package_exception - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_check_paths_are_not_valid - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_check_paths_are_valid - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_get_closure_size - FileExistsError: [Errno 17] File exists: 'stores'
ERROR tests/unit/test_store_logic.py::test_get_closure - FileExistsError: [Errno 17] File exists: 'stores'
```

https://docs.python.org/3/library/tempfile.html

2024-04-28 18:45 UTC, snejugal commented on src/logic/core.py
> +        Path(path).chmod(0o755)
```
[snejugal@snejugal:~/inno/sqr/nix-store-web]$ cat src/logic/core.py | rg chmod
        Path(path).chmod(0o755)

[snejugal@snejugal:~/inno/sqr/nix-store-web]$ nix build --store ./stores/foo nixpkgs#hello

[snejugal@snejugal:~/inno/sqr/nix-store-web]$ python3
Python 3.11.9 (main, Apr  2 2024, 08:25:04) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from src.logic.core import remove_store
>>> from pathlib import Path
>>> remove_store(Path("./stores/foo"))
Traceback (most recent call last):
  File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/shutil.py", line 701, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'hello'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snejugal/inno/sqr/nix-store-web/src/logic/core.py", line 38, in remove_store
    rmtree(store, onerror=handle_permission_error)
  File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/shutil.py", line 752, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/shutil.py", line 672, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 1 more time]
  File "/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/lib/python3.11/shutil.py", line 703, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/snejugal/inno/sqr/nix-store-web/src/logic/core.py", line 36, in handle_permission_error
    function(path)
PermissionError: [Errno 13] Permission denied: 'stores/foo/nix/store/yn46i4xx5alh7gs6fpkxk430i34rp2q9-hello-2.12.1/bin/hello'
```

compare that to

```
[snejugal@snejugal:~/inno/sqr/nix-store-web]$ cat src/logic/core.py | rg chmod
        Path(path).parent.chmod(0o755)

[snejugal@snejugal:~/inno/sqr/nix-store-web]$ python3
Python 3.11.9 (main, Apr  2 2024, 08:25:04) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from src.logic.core import remove_store
>>> from pathlib import Path
>>> remove_store(Path("./stores/foo"))
>>>
```

если что-то там на винде не так работает, то винда идёт нафиг, потому что этот проект unix-like-only

2024-04-28 19:54 UTC, SnejUgal commented on api/tests/unit/test_store_endpoints.py
> +    shutil.rmtree("stores", ignore_errors=True)
закрою, раз в самих тестах не возникает проблема с разрешениями

2024-04-28 19:56 UTC, ilnarkhasanov approved these changes

2024-04-28 20:01 UTC, SnejUgal commented on pyproject.toml
> +webdriver-manager = "^4.0.1"
```suggestion
```

кажется, мы не собираемся писать тесты на селениуме

2024-04-28 20:59 UTC, Probirochniy commented on api/tests/unit/test_auth_endpoints.py
> +os.environ["DATABASE_URL"] = "sqlite+aiosqlite:///test.db"
Короче ломается всё, если create_db_and_tables менять. Как и если импорты в функцию переносить. in-memory получилось сделать, закоммичу

2024-04-29 05:41 UTC, SnejUgal requested changes

2024-04-29 05:41 UTC, SnejUgal commented on .gitignore
пофикси `\r\n` тут

2024-04-29 05:41 UTC, SnejUgal commented on .github/workflows/main.yml
тут

2024-04-29 05:41 UTC, SnejUgal commented on flake.nix
особенно тут

2024-04-29 05:41 UTC, snejugal commented on tests/test_recoverability.py
> +    stores_database = [store[0].name for store in result.all()]
лезть надо не в нашу бд а в `{store}/nix/var/nix/db/db.sqlite` 

```
$ nix run nixpkgs#sqlite ./stores/foo/nix/var/nix/db/db.sqlite
SQLite version 3.45.2 2024-03-12 11:06:23
Enter ".help" for usage hints.
sqlite> .headers on
sqlite> select * from validpaths limit 1;
id|path|hash|registrationTime|deriver|narSize|ultimate|sigs|ca
1|/nix/store/ypkhxink7miy8gw2mi88jlacl213cg4d-flake-registry.json|sha256:0d849669f864cf4d6bd1cb5ce68041a825302250bcb7a19b3acd79bbe173e85c|1714369092||7504|||fixed:sha256:1h5d2vbjfa4ixxkgir0c90samfzdawv95vw46hf67mscfgsd8dwz
```

2024-04-29 05:41 UTC, snejugal commented on tests/test_recoverability.py
> +    stores_database = [store[0].name for store in result.all()]
и ты кажется ничего не ставишь поэтому сравниваешь пустой список с пустым

2024-04-29 05:42 UTC, SnejUgal commented on src/app.py
тут тоже `\r\n`

2024-04-29 16:02 UTC, SnejUgal approved these changes

2024-04-29 16:04 UTC, merged