Add FastAPI app
fedor-ivn/nix-store-explorer pull request #6
Opened 2024-04-09 11:17 UTC by ilnarkhasanov

2024-04-09 18:23 UTC, SnejUgal requested changes

2024-04-09 18:23 UTC, SnejUgal commented on api/store/router.py
это всё конечно очень хорошо, но не restful. по ресту ж как: есть какой-то объект, у него есть урл, а на нём вызываются действия. соответственно, рестоводы сделали бы так:

- `POST /store` чтобы создать стор;
- `GET /store/{name}` чтобы получить информацию о сторе;
- `DELETE /store/{name}` чтобы удалить стор;
- `POST /store/{name}/package` чтобы добавить пакет;
- `DELETE /store/{name}/package` чтобы удалить пакет;
- ...

сможешь переделать апи соответствующим образом?

2024-04-09 18:23 UTC, SnejUgal commented on api/store/models/path.py
> +    difference: list[str]
тут наверно должен быть один список пакетов, которые есть в store_1 и нет в store_2, и другой список пакетов, которых нет в store_1 но есть в store_2

2024-04-09 18:23 UTC, SnejUgal commented on api/store/models/closure.py
> +    difference: list[Package]
ну и соответственно тут тоже. кажется можно один и тот же тип заюзать для difference

2024-04-09 18:34 UTC, SnejUgal commented on api/store/models/path.py
> +    difference: list[str]
https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-store-diff-closures

вот это кажется лучше подходит

2024-04-10 05:50 UTC, deemp commented on api/store/models/path.py
> +    difference: list[str]
> тут наверно должен быть один список пакетов, которые есть в store_1 и нет в store_2, и другой список пакетов, которых нет в store_1 но есть в store_2

difference на множествах дает одно множество, так что изначально имелся в виду один список. Но можете и два выдавать, как ты описал.

2024-04-10 07:56 UTC, ilnarkhasanov commented on api/store/router.py
> +def get_closures_difference(package_1_id: int, package_2_id: int):
@SnejUgal 

как думаешь, как лучше поступить? искать по имени или id?

2024-04-10 08:04 UTC, ilnarkhasanov commented on api/store/router.py
> +def get_closures_difference(package_1_id: int, package_2_id: int):
такой же вопрос про paths

2024-04-10 08:39 UTC, SnejUgal commented on api/store/router.py
> +def get_closures_difference(package_1_id: int, package_2_id: int):
имхо и сторы, и пакеты стоит искать по имени

2024-04-10 08:48 UTC, SnejUgal commented on api/store/router.py
> +    return User(id=1)
если у нас уже есть `Store`, то может стоит сделать просто `GET /store/{name}`, и в ответе в том числе будет owner_id?

2024-04-10 08:48 UTC, SnejUgal commented on api/store/router.py
> +def delete_package(store_name: str, package_request: PackageRequest = Body(...)):
мб `DELETE /store/{store_name}/package/{package_name}`?

2024-04-10 08:48 UTC, SnejUgal commented on api/store/router.py
> +    return paths_difference
здесь предлагаю `GET /store/{name}/difference/{other}`

2024-04-10 08:48 UTC, SnejUgal commented on api/store/router.py
> +def get_closures_difference(package_1_id: int, package_2_id: int):
здесь предлагаю `GET /store/{store_name}/package/{package_name}/closure-difference/{other_package_name}`. как минимум, мы точно должны знать стор, чтобы достать пакеты, которые будет диффать

2024-04-10 08:48 UTC, SnejUgal commented on api/store/router.py
> +    return PackagePresence(present=True)
ну и здесь имхо можно возвращать информацию о размере closure

2024-04-10 10:17 UTC, ilnarkhasanov commented on api/store/router.py
> +def get_closures_difference(package_1_id: int, package_2_id: int):
@SnejUgal 

пакеты могут быть из разных сторов?

2024-04-10 10:24 UTC, SnejUgal commented on api/store/router.py
> +def get_closures_difference(package_1_id: int, package_2_id: int):
лучше уточнить у @deemp, мне кажется

2024-04-10 10:50 UTC, SnejUgal commented on api/store/router.py
> +    return closure_size
а нужен этот эндпоинт, если closure_size уже отдаётся по `/{store_name}/package/{package_name}`?

2024-04-10 11:41 UTC, snejugal approved these changes

2024-04-10 13:11 UTC, fedor-ivn approved these changes

2024-04-10 13:14 UTC, merged