Add interactive forms for all current routes
fedor-ivn/nix-store-explorer pull request #9
Opened 2024-04-12 15:50 UTC by FurryLord

Closes #3

2024-04-13 16:02 UTC, snejugal commented on streamlit/frontend.py
> +                f"{base_url}/store/{store_name}/package", json=payload)
у ильнара где-то нужно payload через тело прокидывать? если да, надо ему ишью зафигачить, урла предостаточно

2024-04-13 17:43 UTC, ilnarkhasanov commented on streamlit/frontend.py
> +                f"{base_url}/store/{store_name}/package", json=payload)
@SnejUgal

а в чём проблема пейлоада через тело?

2024-04-13 18:32 UTC, SnejUgal commented on streamlit/frontend.py
> +                f"{base_url}/store/{store_name}/package", json=payload)
так, ну название пакета ещё мб норм, его в урле нет. но вот store_id точно не нужен, потому что в урле уже есть название стора

2024-04-15 12:39 UTC, fedor-ivn requested changes
еще нужно ребейзнуть ветку от мейна, чтобы ci/cd в пр появилась

2024-04-15 18:14 UTC, SnejUgal approved these changes

2024-04-15 18:14 UTC, fedor-ivn approved these changes

2024-04-15 18:14 UTC, fedor-ivn approved these changes

2024-04-15 18:15 UTC, merged